const includedAPIs = [
  'GET:/api/profile/',
  'PUT:/api/profile/',
  'DELETE:/api/profile/',
  'POST:/api/product/',
  'PUT:/api/product/',
  'DELETE:/api/product/',
  'POST:/api/category/',
  'PUT:/api/category/',
  'DELETE:/api/category/',
  'POST:/api/subCategory/',
  'PUT:/api/subCategory/',
  'DELETE:/api/subCategory/',
  'POST:/api/prompt/',
  'PUT:/api/prompt/',
  'DELETE:/api/prompt/',
  'GET:/api/payment/',
  'GET:/api/payment/webhook',
  'POST:/api/payment/order',
  'POST:/api/payment/success',
  'POST:/api/payment/fail',
]
export default includedAPIs
